package com.jupiter.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.id
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.title
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.gmt_create
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.gmt_modified
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.creator
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.comment_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.view_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.like_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.tag
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community_question.description
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.id
     *
     * @return the value of community_question.id
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.id
     *
     * @param id the value for community_question.id
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.title
     *
     * @return the value of community_question.title
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.title
     *
     * @param title the value for community_question.title
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.gmt_create
     *
     * @return the value of community_question.gmt_create
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.gmt_create
     *
     * @param gmtCreate the value for community_question.gmt_create
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.gmt_modified
     *
     * @return the value of community_question.gmt_modified
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.gmt_modified
     *
     * @param gmtModified the value for community_question.gmt_modified
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.creator
     *
     * @return the value of community_question.creator
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.creator
     *
     * @param creator the value for community_question.creator
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.comment_count
     *
     * @return the value of community_question.comment_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.comment_count
     *
     * @param commentCount the value for community_question.comment_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.view_count
     *
     * @return the value of community_question.view_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.view_count
     *
     * @param viewCount the value for community_question.view_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.like_count
     *
     * @return the value of community_question.like_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.like_count
     *
     * @param likeCount the value for community_question.like_count
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.tag
     *
     * @return the value of community_question.tag
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.tag
     *
     * @param tag the value for community_question.tag
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community_question.description
     *
     * @return the value of community_question.description
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community_question.description
     *
     * @param description the value for community_question.description
     *
     * @mbg.generated Tue Aug 20 17:39:22 GMT+08:00 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}